[package]

name = "session"
version = "0.1.0"
authors = ["Zach Pomerantz <zmp@umich.edu>"]

[dependencies.iron]

git = "https://github.com/iron/iron.git"

[dependencies.iron-test]

git = "https://github.com/reem/iron-test.git"

[dependencies]
hyper = "0.5"
